apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-demo-app
  template:
    metadata:
      labels:
        app: openshift-demo-app
    spec:
      containers:
        - name: openshift-demo-app
          image: vnikolaew/openshift-demo-app:1.0.1
          ports:
            - containerPort: 8080
              
---

apiVersion: v1
kind: Service
metadata:
  name: openshift-demo-lb-service
spec:
  selector:
    app: openshift-demo-app
  ports:
    - name: lb-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10